/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-HIDAPI.h
 #	source generated by 4D Plugin Wizard
 #	Project : HIDAPI
 #	author : miyako
 #	2020/02/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_HIDAPI_H
#define PLUGIN_HIDAPI_H

#include "4DPluginAPI.h"
#include "hidapi/hidapi.h"
#include "4DPlugin-JSON.h"

#include "C_BLOB.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"

#include <mutex>

#pragma mark -

void hid_enumerate(PA_PluginParameters params);
void hid_open(PA_PluginParameters params);
void hid_open_path(PA_PluginParameters params);
void hid_close(PA_PluginParameters params);
void hid_write(PA_PluginParameters params);
void hid_read(PA_PluginParameters params);
void hid_send_feature_report(PA_PluginParameters params);
void hid_get_feature_report(PA_PluginParameters params);
void hid_set_nonblocking(PA_PluginParameters params);

void OnStartup();
void OnExit();

#define STRING_BUFFER_LENGTH 1023
#define BINARY_BUFFER_LENGTH 0x80000

#endif /* PLUGIN_HIDAPI_H */
